# Generated by Django 3.2.4 on 2021-06-17 22:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_entrada',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Fecha cuando introdujeron el producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='canasta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.cliente'),
        ),
        migrations.AlterField(
            model_name='categorias',
            name='descripcion',
            field=models.TextField(help_text='Descripcion de la categoría'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(help_text='Número de contacto', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(help_text='Descripción del producto'),
        ),
    ]
