# Generated by Django 3.2.4 on 2021-06-24 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_rename_categorias_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la sección en la que se encuentra el producto', max_length=50)),
                ('descripcion', models.TextField(help_text='Descripcion de la seccion en la que se encuentra el producto')),
            ],
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
