# Generated by Django 3.2.4 on 2021-06-24 21:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20210623_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secciones',
            name='nombre',
        ),
        migrations.AddField(
            model_name='secciones',
            name='rubro',
            field=models.CharField(default=django.utils.timezone.now, help_text='El rubro al que pertenece cada producto', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='rubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.secciones'),
        ),
    ]
