# Generated by Django 3.2.4 on 2021-06-24 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_auto_20210624_1808'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Secciones',
            new_name='Categoria',
        ),
    ]
