# Generated by Django 3.2.4 on 2021-06-24 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_rename_secciones_categoria'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Secciones',
        ),
    ]
