# Generated by Django 3.2.4 on 2021-06-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_rename_categoria_secciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='rubro',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Secciones',
        ),
    ]
