# Generated by Django 3.2.4 on 2021-06-24 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_auto_20210624_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubro', models.CharField(help_text='El rubro al que pertenece cada producto', max_length=50)),
                ('descripcion', models.TextField(help_text='Descripcion de la seccion en la que se encuentra el producto')),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='rubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.categoria'),
        ),
    ]
